{
 "title": "Open PRs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "squad_filter",
    "label": "Squad",
    "query": "SELECT DISTINCT \"Squad\"\nFROM open_prs\nORDER BY \"Squad\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Count of Orphaned PRs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM orphaned_prs WHERE \"Squad\" IN ($squad_filter); "
    }
   ]
  },
  {
   "title": "Open Child PRs Details Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Parent PR Number\", \"Name Service\", \"Squad\", \"Auto PR URL\", \"Auto PR State\", \"If merged\", \"Parent PR State\", \"Parent PR merged\", \"Github PR State\", \"Github PR Merged\" FROM orphaned_prs WHERE \"Squad\" IN ($squad_filter);"
    }
   ]
  },
  {
   "title": "Total Count of Child PRs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM \"open_prs\" WHERE \"Squad\" IN ($squad_filter);"
    }
   ]
  },
  {
   "title": "Open Child PRs Details Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"open_prs\" WHERE \"Squad\" IN ($squad_filter);\r\n"
    }
   ]
  },
  { "title": "Diagrams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Open PRs by Squads",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Squad\", COUNT(*) FROM \"open_prs\" GROUP BY \"Squad\"\r\n"
    }
   ]
  },
  {
   "title": "Open PRs by Services",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Name Service\", COUNT(*) FROM \"open_prs\" GROUP BY \"Name Service\""
    }
   ]
  }
 ]
}