{
 "title": "Open Issues Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "squad_issues",
    "label": "Squad",
    "query": "SELECT DISTINCT \"Squad\"\nFROM open_issues\nORDER BY \"Squad\";"
   },
   {
    "name": "env_issues",
    "label": "Environment",
    "query": "SELECT DISTINCT \"Environment\"\nFROM open_issues\nORDER BY \"Environment\";"
   },
   { "name": "sort_duration", "label": "Duration", "query": "ASC,DESC" }
  ]
 },
 "panels": [
  {
   "title": "Gitea count of issues",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM open_issues WHERE \"Environment\" = 'Gitea' AND \"Squad\" IN ($squad_issues) AND \"Environment\" IN ($env_issues)"
    }
   ]
  },
  {
   "title": "Total count of issues",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM open_issues WHERE \"Squad\" IN ($squad_issues) AND \"Environment\" IN ($env_issues)"
    }
   ]
  },
  {
   "title": "Github count of issues",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM open_issues WHERE \"Environment\" = 'Github' AND \"Squad\" IN ($squad_issues) AND \"Environment\" IN ($env_issues)"
    }
   ]
  },
  {
   "title": "Open Issues: Detailed",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM open_issues WHERE \"Squad\" IN ($squad_issues) AND \"Environment\" IN ($env_issues) ORDER BY \"Duration\"::numeric $sort_duration;"
    }
   ]
  },
  {
   "title": "Open Issues by Duration",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN \"Duration\"::numeric BETWEEN 0 AND 7 THEN '0-7 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 8 AND 14 THEN '8-14 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 15 AND 21 THEN '15-21 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 22 AND 31 THEN '22-31 days'\r\n        ELSE '32-666 days'\r\n    END AS duration_range,\r\n    COUNT(*) as issue_count\r\nFROM open_issues\r\nGROUP BY duration_range\r\nORDER BY duration_range;\r\n"
    }
   ]
  },
  {
   "title": "Open PRs by Services",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Service Name\", COUNT(*) FROM \"open_issues\" GROUP BY \"Service Name\""
    }
   ]
  },
  {
   "title": "Open PRs by Squads",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Squad\", COUNT(*) FROM \"open_issues\" GROUP BY \"Squad\"\r\n"
    }
   ]
  }
 ]
}