{
 "title": "Open PRs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "squad_filter",
    "label": "Squad",
    "query": "SELECT DISTINCT \"Category\"\nFROM repo_title_category\nORDER BY \"Category\";"
   },
   { "name": "env", "label": "Environment", "query": "Gitea, Github" }
  ]
 },
 "panels": [
  {
   "title": "Total Count of Orphaned PRs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM orphaned_prs WHERE \"Squad\" IN ($squad_filter); "
    }
   ]
  },
  {
   "title": "Orphaned Child PRs Details Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM orphaned_prs WHERE \"Squad\" IN ($squad_filter);"
    }
   ]
  },
  { "title": "${env}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "env" },
  {
   "title": "Total Count of ${env} Child PRs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM \"open_prs\" WHERE \"Squad\" IN ($squad_filter) AND \"Environment\" IN ($env);"
    }
   ]
  },
  {
   "title": "Open ${env} Child PRs Details Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"open_prs\" WHERE \"Squad\" IN ($squad_filter) AND \"Environment\" IN ($env);\r\n"
    }
   ]
  },
  { "title": "Diagrams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "${env}: open PRs by Squads",
   "type": "barchart",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Squad\", COUNT(*) FROM \"open_prs\" WHERE \"Environment\" IN ($env) GROUP BY \"Squad\"\r\n"
    }
   ]
  },
  {
   "title": "${env}: open PRs by Services",
   "type": "barchart",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Service Name\", COUNT(*) FROM \"open_prs\" WHERE \"Environment\" IN ($env) GROUP BY \"Service Name\"\r\n"
    }
   ]
  }
 ]
}