{
 "title": "Open Issues Eco",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Open Issues by Duration",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN \"Duration\"::numeric BETWEEN 0 AND 7 THEN '0-7 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 8 AND 14 THEN '8-14 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 15 AND 21 THEN '15-21 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 22 AND 31 THEN '22-31 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 32 AND 100 THEN '32-100 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 101 AND 250 THEN '101-250 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 251 AND 365 THEN '251-365 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 366 AND 730 THEN '366-730 days'\r\n        WHEN \"Duration\"::numeric BETWEEN 731 AND 1000 THEN '731-1000 days'\r\n        ELSE '1001-1500 days'\r\n    END AS duration_range,\r\n    COUNT(*) as issue_count\r\nFROM open_issues_eco \r\nGROUP BY duration_range\r\nORDER BY duration_range;\r\n"
    }
   ]
  },
  {
   "title": "Total count of issues",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT id FROM open_issues_eco "
    }
   ]
  },
  {
   "title": "Open Issues by Repo Names",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Repo Name\", COUNT(*) FROM open_issues_eco GROUP BY \"Repo Name\" ORDER BY \"Repo Name\";"
    }
   ]
  },
  {
   "title": "Open Issues: Detailed",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT * FROM open_issues_eco ORDER BY \"Duration\"::numeric $sort_duration;"
    }
   ]
  }
 ]
}